env:
  browser: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier

overrides: []

parserOptions:
  ecmaVersion: latest
  sourceType: module

plugins:
  - react
  - react-hooks

rules:
  react/prop-types: off
  react/react-in-jsx-scope: off
  react-hooks/exhaustive-deps: warn
  react-hooks/rules-of-hooks: error
  react/no-unknown-property: [error, {ignore: [css]}] # for emotion

settings:
  react:
    version: detect